# Generated by Django 5.1.2 on 2024-10-18 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suit",
                    models.IntegerField(
                        choices=[
                            (4, "Spade"),
                            (3, "Heart"),
                            (2, "Diamond"),
                            (1, "Club"),
                        ]
                    ),
                ),
                (
                    "rank",
                    models.IntegerField(
                        choices=[
                            (2, "Two"),
                            (3, "Three"),
                            (4, "Four"),
                            (5, "Five"),
                            (6, "Six"),
                            (7, "Seven"),
                            (8, "Eight"),
                            (9, "Nine"),
                            (10, "Ten"),
                            (11, "Jack"),
                            (12, "Queen"),
                            (13, "King"),
                            (14, "Ace"),
                        ]
                    ),
                ),
            ],
            options={
                "unique_together": {("suit", "rank")},
            },
        ),
        migrations.CreateModel(
            name="Hand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveIntegerField()),
                (
                    "card1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hand1s",
                        to="hand_ranker.card",
                    ),
                ),
                (
                    "card2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hand2s",
                        to="hand_ranker.card",
                    ),
                ),
                (
                    "card3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hand3s",
                        to="hand_ranker.card",
                    ),
                ),
                (
                    "card4",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hand4s",
                        to="hand_ranker.card",
                    ),
                ),
                (
                    "card5",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hand5s",
                        to="hand_ranker.card",
                    ),
                ),
            ],
            options={
                "unique_together": {("card1", "card2", "card3", "card4", "card5")},
            },
        ),
    ]
