# Generated by Django 5.1.2 on 2024-10-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hand_ranker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hand",
            name="hand_type",
            field=models.IntegerField(
                choices=[
                    (9, "Straight Flush"),
                    (8, "Quads"),
                    (7, "Full House"),
                    (6, "Flush"),
                    (5, "Staight"),
                    (4, "Trips"),
                    (3, "Two Pair"),
                    (2, "Pair"),
                    (1, "High Card"),
                ],
            ),
            preserve_default=False,
        ),
    ]
